<a href="https://colab.research.google.com/github/dskimds/KOSA-Big-Data_Vision/blob/main/ML/0_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# from numpy import exp, array, random, dot

In [2]:
import numpy as np

In [18]:
training_set_inputs = np.array([[0, 0], [1, 1], [1, 0], [0, 1]])

In [19]:
training_set_inputs

array([[0, 0],
       [1, 1],
       [1, 0],
       [0, 1]])

In [20]:
training_set_outputs = np.array([0, 1, 1, 0]).reshape(-1,1)
#training_set_outputs = array([[0, 1, 1, 0]]).T

In [21]:
training_set_outputs

array([[0],
       [1],
       [1],
       [0]])

In [22]:
training_set_outputs.shape

(4, 1)

In [23]:
training_set_outputs

array([[0],
       [1],
       [1],
       [0]])

In [24]:
training_set_outputs.shape

(4, 1)

In [25]:
training_set_inputs.shape

(4, 2)

In [26]:
np.random.seed(1)
synaptic_weights = 2 * np.random.random((2, 1)) - 1

for iteration in range(100000):
    output = 1 / (1 + np.exp(-(np.dot(training_set_inputs, synaptic_weights))))
    synaptic_weights += np.dot(training_set_inputs.T, (training_set_outputs - output) * output * (1 - output))

In [27]:
synaptic_weights

array([[11.2888138 ],
       [-5.54244987]])

In [29]:
print (1 / (1 + np.exp(-(np.dot(np.array([0, 1]), synaptic_weights)))))

[0.00390164]
